steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud functions deploy costor-notify \
          --runtime=nodejs20 \
          --trigger-http \
          --entry-point=main \
          --region=asia-northeast1 \
          --source=functions \
          --set-env-vars=DATASET_ID=costor_billing_export \
          --secret-environment-variables=DISCORD_WEBHOOK_URL=costor-discord-token:latest \
          --allow-unauthenticated

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/costor-discord-token/versions/latest
      env: DISCORD_WEBHOOK_URL
